### ISSUE TITLE
Can't install via gemspec

### ISSUE THREAD

**Issue by gbuesing** [masa16/narray-devel#2]
If I try building from gemspec, I get an error:

```
$ gem build narray-devel.gemspec 
Invalid gemspec in [narray-devel.gemspec]: cannot load such file -- narray/devel/version
ERROR:  Error loading gemspec. Aborting.
```

How do I install? Thanks!

**Comment by masa16** [comment]
This is corrected by the latest commit.
Please note that this version is under development and might be drastically changed.

**Comment by gbuesing** [comment]
Thank you for updating the gemspec. With this latest commit, I can now run ```gem build`` just fine, but when I run ```gem install```, I get an error. Final part of output is:

```
1 warning generated.
compiling types/sfloat.c
compiling types/dfloat.c
compiling types/scomplex.c
compiling types/dcomplex.c
compiling types/robject.c
compiling math.c
compiling SFMT.c
compiling struct.c
compiling rand.c
linking shared-object narray.bundle
duplicate symbol _na_cStep in:
    narray.o
    step.o
duplicate symbol _cBit in:
    narray.o
    types/bit.o
duplicate symbol _cRObject in:
    narray.o
    types/robject.o
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [narray.bundle] Error 1
ERROR:  Error installing narray-devel-0.9.0.1.gem:
	ERROR: Failed to build gem native extension.
```

I'm on Mac OS X Yosemite, and I tried with both Ruby 2.2.0 and Ruby 2.1.5.

**Comment by masa16** [comment]
Fixed. Thank you for reporting.

**Comment by gbuesing** [comment]
Great, gem installs now without error. Thank you!

**Comment by gbuesing** [comment]
To make getting up and running even easier:  I created a pull request which allows you to simply ```require 'narray-devel'``` instead of ```gem 'narray-devel'; require 'narray'```: https://github.com/masa16/narray-devel/pull/3
